--------------------------------------------------------
--  File created - Wednesday-August-29-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "ROY001"."ADMIN" 
   (	"ADMIN_ID" VARCHAR2(20 BYTE), 
	"ADMIN_PASSWORD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CLNT_TRA_INFO
--------------------------------------------------------

  CREATE TABLE "ROY001"."CLNT_TRA_INFO" 
   (	"CLNT_NAME" VARCHAR2(20 BYTE), 
	"CLNT_ID" VARCHAR2(20 BYTE), 
	"LOAN" VARCHAR2(20 BYTE) DEFAULT 000000, 
	"WITHDRAW" VARCHAR2(20 BYTE) DEFAULT 000000, 
	"INSURANCE" VARCHAR2(20 BYTE) DEFAULT 000000, 
	"CURRENT_AMOUNT" VARCHAR2(20 BYTE) DEFAULT 000000
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMI
--------------------------------------------------------

  CREATE TABLE "ROY001"."EMI" 
   (	"CLNT_NAME" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"CLNT_ID" VARCHAR2(20 BYTE), 
	"LOAN" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"FIRST_M" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"SECOND_M" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"THIRD_M" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"FOURTH_M" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"FIVE_M" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"SIX_M" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"SEVEN_M" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"EIGHT_M" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"NINE_M" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"TEN_M" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"ELEVEN_M" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"TWELVE_M" VARCHAR2(20 BYTE) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REGISTRATION
--------------------------------------------------------

  CREATE TABLE "ROY001"."REGISTRATION" 
   (	"CLNT_GENDER" VARCHAR2(20 BYTE), 
	"CLNT_NAME" VARCHAR2(20 BYTE), 
	"EMAIL_ID" VARCHAR2(20 BYTE), 
	"DATE_OF_BIRTH" VARCHAR2(20 BYTE), 
	"ACCOUNT_TYPE" VARCHAR2(20 BYTE), 
	"CLNT_PASSWORD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ROY001.ADMIN
SET DEFINE OFF;
Insert into ROY001.ADMIN (ADMIN_ID,ADMIN_PASSWORD) values ('ROY','04322');
REM INSERTING into ROY001.CLNT_TRA_INFO
SET DEFINE OFF;
Insert into ROY001.CLNT_TRA_INFO (CLNT_NAME,CLNT_ID,LOAN,WITHDRAW,INSURANCE,CURRENT_AMOUNT) values ('ss','ss','100.0','100','0','900');
Insert into ROY001.CLNT_TRA_INFO (CLNT_NAME,CLNT_ID,LOAN,WITHDRAW,INSURANCE,CURRENT_AMOUNT) values ('ff','ff','0','100','0','400');
Insert into ROY001.CLNT_TRA_INFO (CLNT_NAME,CLNT_ID,LOAN,WITHDRAW,INSURANCE,CURRENT_AMOUNT) values ('aa','aa','11122.0','500','1111','11411');
Insert into ROY001.CLNT_TRA_INFO (CLNT_NAME,CLNT_ID,LOAN,WITHDRAW,INSURANCE,CURRENT_AMOUNT) values ('mr. x','x@yahoo.com','111','500','1000','31000');
Insert into ROY001.CLNT_TRA_INFO (CLNT_NAME,CLNT_ID,LOAN,WITHDRAW,INSURANCE,CURRENT_AMOUNT) values ('p','p','0.0','500','0','49500');
Insert into ROY001.CLNT_TRA_INFO (CLNT_NAME,CLNT_ID,LOAN,WITHDRAW,INSURANCE,CURRENT_AMOUNT) values ('ww','ww','0','1000','0','4000');
Insert into ROY001.CLNT_TRA_INFO (CLNT_NAME,CLNT_ID,LOAN,WITHDRAW,INSURANCE,CURRENT_AMOUNT) values ('mr a','a','0','0','0','0');
REM INSERTING into ROY001.EMI
SET DEFINE OFF;
Insert into ROY001.EMI (CLNT_NAME,CLNT_ID,LOAN,FIRST_M,SECOND_M,THIRD_M,FOURTH_M,FIVE_M,SIX_M,SEVEN_M,EIGHT_M,NINE_M,TEN_M,ELEVEN_M,TWELVE_M) values ('v','a',null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into ROY001.EMI (CLNT_NAME,CLNT_ID,LOAN,FIRST_M,SECOND_M,THIRD_M,FOURTH_M,FIVE_M,SIX_M,SEVEN_M,EIGHT_M,NINE_M,TEN_M,ELEVEN_M,TWELVE_M) values ('David','d@gmail.com','3.0517578E-5','200.00003','200.00003','200.00003','200.00003','200.00003',null,null,null,null,null,null,null);
Insert into ROY001.EMI (CLNT_NAME,CLNT_ID,LOAN,FIRST_M,SECOND_M,THIRD_M,FOURTH_M,FIVE_M,SIX_M,SEVEN_M,EIGHT_M,NINE_M,TEN_M,ELEVEN_M,TWELVE_M) values ('antu','antu@gmail.com','400.0','100.0','150.0','150.0','500.0',null,null,null,null,null,null,null,null);
Insert into ROY001.EMI (CLNT_NAME,CLNT_ID,LOAN,FIRST_M,SECOND_M,THIRD_M,FOURTH_M,FIVE_M,SIX_M,SEVEN_M,EIGHT_M,NINE_M,TEN_M,ELEVEN_M,TWELVE_M) values ('aa','aa','11122.0','3428.5715','3428.5715','3428.5715','3428.5715','3428.5715','3428.5715','3428.5715',null,null,null,null,null);
Insert into ROY001.EMI (CLNT_NAME,CLNT_ID,LOAN,FIRST_M,SECOND_M,THIRD_M,FOURTH_M,FIVE_M,SIX_M,SEVEN_M,EIGHT_M,NINE_M,TEN_M,ELEVEN_M,TWELVE_M) values ('p','p','0.0','200.0','200.0','200.0','200.0','200.0',null,null,null,null,null,null,null);
Insert into ROY001.EMI (CLNT_NAME,CLNT_ID,LOAN,FIRST_M,SECOND_M,THIRD_M,FOURTH_M,FIVE_M,SIX_M,SEVEN_M,EIGHT_M,NINE_M,TEN_M,ELEVEN_M,TWELVE_M) values ('v','v','0.0','5000.0','5000.0','5000.0','5000.0','5000.0','5000.0','5000.0','5000.0','5000.0','5000.0','416.66666','416.66666');
Insert into ROY001.EMI (CLNT_NAME,CLNT_ID,LOAN,FIRST_M,SECOND_M,THIRD_M,FOURTH_M,FIVE_M,SIX_M,SEVEN_M,EIGHT_M,NINE_M,TEN_M,ELEVEN_M,TWELVE_M) values ('c','c','0.0','500.0','500.0','500.0','500.0',null,null,null,null,null,null,null,null);
Insert into ROY001.EMI (CLNT_NAME,CLNT_ID,LOAN,FIRST_M,SECOND_M,THIRD_M,FOURTH_M,FIVE_M,SIX_M,SEVEN_M,EIGHT_M,NINE_M,TEN_M,ELEVEN_M,TWELVE_M) values ('x','x','0.0','200.0','200.0','200.0','200.0','200.0',null,null,null,null,null,null,null);
Insert into ROY001.EMI (CLNT_NAME,CLNT_ID,LOAN,FIRST_M,SECOND_M,THIRD_M,FOURTH_M,FIVE_M,SIX_M,SEVEN_M,EIGHT_M,NINE_M,TEN_M,ELEVEN_M,TWELVE_M) values ('ss','ss',null,null,null,null,null,null,null,null,null,null,null,null,null);
REM INSERTING into ROY001.REGISTRATION
SET DEFINE OFF;
Insert into ROY001.REGISTRATION (CLNT_GENDER,CLNT_NAME,EMAIL_ID,DATE_OF_BIRTH,ACCOUNT_TYPE,CLNT_PASSWORD) values ('Male','c','d','08-08-2018','GeneralAccount','c');
Insert into ROY001.REGISTRATION (CLNT_GENDER,CLNT_NAME,EMAIL_ID,DATE_OF_BIRTH,ACCOUNT_TYPE,CLNT_PASSWORD) values ('Male','x','x','01-08-2018','StudentAccount','123');
Insert into ROY001.REGISTRATION (CLNT_GENDER,CLNT_NAME,EMAIL_ID,DATE_OF_BIRTH,ACCOUNT_TYPE,CLNT_PASSWORD) values ('Male','cook','cc','31-07-2018','StudentAccount','cc');
Insert into ROY001.REGISTRATION (CLNT_GENDER,CLNT_NAME,EMAIL_ID,DATE_OF_BIRTH,ACCOUNT_TYPE,CLNT_PASSWORD) values ('Male','antu','antu@gmail.com','21-06-1994','GeneralAccount','111');
Insert into ROY001.REGISTRATION (CLNT_GENDER,CLNT_NAME,EMAIL_ID,DATE_OF_BIRTH,ACCOUNT_TYPE,CLNT_PASSWORD) values ('Male','s','s','01-08-2018','StudentAccount','s');
Insert into ROY001.REGISTRATION (CLNT_GENDER,CLNT_NAME,EMAIL_ID,DATE_OF_BIRTH,ACCOUNT_TYPE,CLNT_PASSWORD) values ('Female','v','a','31-07-2018','StudentAccount','123');
Insert into ROY001.REGISTRATION (CLNT_GENDER,CLNT_NAME,EMAIL_ID,DATE_OF_BIRTH,ACCOUNT_TYPE,CLNT_PASSWORD) values ('Male','aa','aa','30-07-2018','StudentAccount','aa');
Insert into ROY001.REGISTRATION (CLNT_GENDER,CLNT_NAME,EMAIL_ID,DATE_OF_BIRTH,ACCOUNT_TYPE,CLNT_PASSWORD) values ('Male','ss','ss','05-08-2018','StudentAccount','ss');
Insert into ROY001.REGISTRATION (CLNT_GENDER,CLNT_NAME,EMAIL_ID,DATE_OF_BIRTH,ACCOUNT_TYPE,CLNT_PASSWORD) values ('Male','ff','ff','01-08-2018','StudentAccount','ff');
Insert into ROY001.REGISTRATION (CLNT_GENDER,CLNT_NAME,EMAIL_ID,DATE_OF_BIRTH,ACCOUNT_TYPE,CLNT_PASSWORD) values ('Male','ww','ww','01-08-2018','StudentAccount','ww');
Insert into ROY001.REGISTRATION (CLNT_GENDER,CLNT_NAME,EMAIL_ID,DATE_OF_BIRTH,ACCOUNT_TYPE,CLNT_PASSWORD) values ('Female','p','p','03-08-2018','GeneralAccount','pp');
Insert into ROY001.REGISTRATION (CLNT_GENDER,CLNT_NAME,EMAIL_ID,DATE_OF_BIRTH,ACCOUNT_TYPE,CLNT_PASSWORD) values ('Male','mr a','a','01-08-2018','GeneralAccount','a');
Insert into ROY001.REGISTRATION (CLNT_GENDER,CLNT_NAME,EMAIL_ID,DATE_OF_BIRTH,ACCOUNT_TYPE,CLNT_PASSWORD) values ('Male','a','a','31-07-2018','StudentAccount','a');
--------------------------------------------------------
--  DDL for Index CLNT_TRA_INFO_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROY001"."CLNT_TRA_INFO_UK1" ON "ROY001"."CLNT_TRA_INFO" ("CLNT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EMI_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROY001"."EMI_UK1" ON "ROY001"."EMI" ("CLNT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CLNT_TRA_INFO
--------------------------------------------------------

  ALTER TABLE "ROY001"."CLNT_TRA_INFO" ADD CONSTRAINT "CLNT_TRA_INFO_UK1" UNIQUE ("CLNT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMI
--------------------------------------------------------

  ALTER TABLE "ROY001"."EMI" ADD CONSTRAINT "EMI_UK1" UNIQUE ("CLNT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REGISTRATION
--------------------------------------------------------

  ALTER TABLE "ROY001"."REGISTRATION" MODIFY ("CLNT_GENDER" NOT NULL ENABLE);
 
  ALTER TABLE "ROY001"."REGISTRATION" MODIFY ("CLNT_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "ROY001"."REGISTRATION" MODIFY ("EMAIL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ROY001"."REGISTRATION" MODIFY ("DATE_OF_BIRTH" NOT NULL ENABLE);
 
  ALTER TABLE "ROY001"."REGISTRATION" MODIFY ("ACCOUNT_TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "ROY001"."REGISTRATION" MODIFY ("CLNT_PASSWORD" NOT NULL ENABLE);
